project_id = "lpkfwxisranmetbtgxrv"

[functions.assistant-ia]
verify_jwt = false

[functions.collecte-veille]
verify_jwt = false

[functions.enrichir-actualite]
verify_jwt = false

[functions.generer-acteurs]
verify_jwt = false

[functions.manage-cron-jobs]
verify_jwt = false

[functions.send-flux-digest]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.generer-newsletter]
verify_jwt = false

[functions.envoyer-newsletter]
verify_jwt = false

[functions.scheduler-newsletter]
verify_jwt = false

[functions.list-users-status]
verify_jwt = false
