project_id = "lpkfwxisranmetbtgxrv"

[functions.assistant-ia]
verify_jwt = false

[functions.collecte-veille]
verify_jwt = false

[functions.enrichir-actualite]
verify_jwt = false

[functions.generer-acteurs]
verify_jwt = false
